[versions]
kotlin = "2.0.0"
coroutines = "1.8.1"
voyager = "1.1.0-beta02"
koin-compose = "1.2.0-Beta5"
ktorfit = "2.0.0"
ktor = "2.3.11"


[libraries]
# Coroutines
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }

# ViewModel
viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.8.0" }

# Preferences
# https://developer.android.com/jetpack/androidx/releases/datastore
datastore-preferences = { module = "androidx.datastore:datastore-preferences-core", version = "1.1.1" }

# Navigation
# https://github.com/adrielcafe/voyager
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screenModel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-lifecycle-kmp = { module = "cafe.adriel.voyager:voyager-lifecycle-kmp", version.ref = "voyager" }

# DI
# https://github.com/InsertKoinIO/koin
koin-core = { module = "io.insert-koin:koin-core", version = "3.5.6" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-compose" }

# Serialization
# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.7.1" }

# Ktorfit
# https://github.com/Foso/Ktorfit
ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }

# Ktor addons - versions should be compatible with Ktorfit
# https://foso.github.io/Ktorfit/#compatibility
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }


[plugins]
jetbrains-compose = { id = "org.jetbrains.compose", version = "1.6.11" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
#noinspection GradleDependency
android-application = { id = "com.android.application", version = "8.2.2" } # newer versions not supported by IDE

# BuildConfig
# https://github.com/yshrsmz/BuildKonfig
buildkonfig = { id = "com.codingfeline.buildkonfig", version = "0.15.1" }

# KSP
# https://mvnrepository.com/artifact/com.google.devtools.ksp/com.google.devtools.ksp.gradle.plugin?repo=central
#noinspection GradleDependency
ksp = { id = "com.google.devtools.ksp", version = "2.0.0-1.0.23" } # 1.0.24 is not working with ktorfit

# Ktorfit
# https://github.com/Foso/Ktorfit
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
