[versions]
kotlin = "2.0.21"
coroutines = "1.9.0"
voyager = "1.1.0-beta03"
koin = "4.0.0"
ktorfit = "2.1.0"
ktor = "2.3.12"
coil = "3.0.0-rc01"
room = "2.7.0-alpha10"
sqlite = "2.5.0-alpha10"


[libraries]
# Coroutines
# https://github.com/Kotlin/kotlinx.coroutines
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }

# ViewModel
viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.8.2" }

# Navigation
# https://github.com/adrielcafe/voyager
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screenModel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-lifecycle-kmp = { module = "cafe.adriel.voyager:voyager-lifecycle-kmp", version.ref = "voyager" }

# DI
# https://github.com/InsertKoinIO/koin
koin-core = { module = "io.insert-koin:koin-core", version = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

# Preferences
# https://developer.android.com/jetpack/androidx/releases/datastore
datastore-preferences = { module = "androidx.datastore:datastore-preferences-core", version = "1.1.1" }

# Serialization
# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.7.3" }

# Ktorfit - network
# https://github.com/Foso/Ktorfit
ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }

# Ktor addons (versions should be compatible with Ktorfit)
# https://foso.github.io/Ktorfit/#compatibility
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }

# Logging (for Ktor)
# https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
logback = { module = "ch.qos.logback:logback-classic", version = "1.5.10" }

# Image loader
# https://github.com/coil-kt/coil
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

# Room DB
# https://developer.android.com/jetpack/androidx/releases/room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# SQLite (Room dependency)
# https://developer.android.com/jetpack/androidx/releases/sqlite
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

# PDF renderer
# https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox
pdfbox = { module = "org.apache.pdfbox:pdfbox", version = "3.0.3" }


[plugins]
# https://github.com/JetBrains/compose-multiplatform
jetbrains-compose = { id = "org.jetbrains.compose", version = "1.7.0-rc01" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version = "8.5.2" }

# BuildConfig
# https://github.com/yshrsmz/BuildKonfig
buildkonfig = { id = "com.codingfeline.buildkonfig", version = "0.15.2" }

# KSP
# https://mvnrepository.com/artifact/com.google.devtools.ksp/com.google.devtools.ksp.gradle.plugin?repo=central
ksp = { id = "com.google.devtools.ksp", version = "2.0.21-1.0.25" }

# Ktorfit - network
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }

# Room
room = { id = "androidx.room", version.ref = "room" }
