[versions]
kotlin = "2.4.0"
compose = "1.11.1"
coroutines = "1.11.0"
koin = "4.2.2"
ktorfit = "2.7.5"
ktor = "3.5.1"
coil = "3.5.0"
room = "2.8.4"
filekit = "0.14.2"
chucker = "4.3.1"
vico = "3.2.3"
markdown = "0.41.0"

android-minSdk = "26"
android-targetSdk = "36"


[libraries]
# Compose
# https://github.com/JetBrains/compose-multiplatform
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version = "1.10.0-alpha05" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "compose" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }

# ViewModel
# https://mvnrepository.com/artifact/org.jetbrains.androidx.lifecycle/lifecycle-viewmodel-navigation3
# Update the version according to the main Compose library dependencies
#noinspection NewerVersionAvailable
viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version = "2.11.0-beta01" }

# Navigation
# https://mvnrepository.com/artifact/org.jetbrains.androidx.navigation3/navigation3-ui
# Update the version according to the main Compose library dependencies
#noinspection NewerVersionAvailable
navigation = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version = "1.1.1" }

# Coroutines
# https://github.com/Kotlin/kotlinx.coroutines
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }

# DI
# https://github.com/InsertKoinIO/koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

# Preferences
# https://github.com/russhwolf/multiplatform-settings
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version = "1.3.0" }

# Serialization
# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.11.0" }

# Ktorfit - network
# https://github.com/Foso/Ktorfit
ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }

# Ktor addons (versions should be compatible with Ktorfit)
# https://foso.github.io/Ktorfit/#compatibility
# https://github.com/ktorio/ktor
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }

# OkHttp
# https://github.com/square/okhttp
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.4.0" }

# Image loader
# https://github.com/coil-kt/coil
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

# Room DB
# https://developer.android.com/jetpack/androidx/releases/room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# SQLite (Room dependency)
# https://developer.android.com/jetpack/androidx/releases/sqlite
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version = "2.7.0" }

# Charts
# https://github.com/patrykandpatrick/vico
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }

# Markdown
# https://github.com/mikepenz/multiplatform-markdown-renderer
markdown-core = { module = "com.mikepenz:multiplatform-markdown-renderer", version.ref = "markdown" }
markdown-material = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "markdown" }


### Desktop-specific libs ###

# Logging (for Ktor)
# https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
logback = { module = "ch.qos.logback:logback-classic", version = "1.5.37" }

# PDF renderer
# https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox
pdfbox = { module = "org.apache.pdfbox:pdfbox", version = "3.0.7" }

# File dialogs
# https://github.com/vinceglb/FileKit
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }

# JNA Platform Library (for COM objects)
# https://github.com/java-native-access/jna
jna-platform = { module = "net.java.dev.jna:jna-platform", version = "5.19.1" }


### Android-specific libs ###

# Desugaring
# https://mvnrepository.com/artifact/com.android.tools/desugar_jdk_libs
desugaring = { module = "com.android.tools:desugar_jdk_libs", version = "2.1.5" }

# AndroidX
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.13.0" }
androidx-preference = { module = "androidx.preference:preference-ktx", version = "1.2.1" }

# Network logger
# https://github.com/ChuckerTeam/chucker
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-noop = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }

# Permissions
# https://github.com/google/accompanist
permissions = { module = "com.google.accompanist:accompanist-permissions", version = "0.37.3" }


[plugins]
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version = "9.0.1" }

# BuildConfig
# https://github.com/yshrsmz/BuildKonfig
buildkonfig = { id = "com.codingfeline.buildkonfig", version = "0.22.0" }

# KSP
# https://mvnrepository.com/artifact/com.google.devtools.ksp/com.google.devtools.ksp.gradle.plugin?repo=central
ksp = { id = "com.google.devtools.ksp", version = "2.3.9" }

# Ktorfit - network
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }

# Room
room = { id = "androidx.room", version.ref = "room" }
